baseURL: https://aafu.pages.dev/
# Uncomment below to use aafu as hugo theme. See instructions in README.md
# theme: aafu
languageCode: en-us
build:
  writeStats: true
params:
  title: なるみき-Profile-
  author: narumiki
  description: Website title
  copyright: >-
    powered by [hugo](https://gohugo.io/) & deployed on
    [Cloudflare](https://www.cloudflare.com/)
  theme:
    mainTheme: dark
    showAttribute: true
    singlePage: false
  favicons:
    use: true
    metas: |2-
              <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
              <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
              <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
              <link rel="manifest" href="site.webmanifest">
              <link rel="mask-icon" href="safari-pinned-tab.svg" color="#252627">
              <link rel="shortcut icon" href="favicon.ico">

  profile:
    name: "なるみき/さぽにん"
    #tagline: Title
    #location: "City Name, ST"
    photo: profile.png
  social:
    title: Links
    list:
      
      - icon: fab fa-twitter
        url: "https://x.com/saponin9000"
        title: Twitter
      - icon: fab fa-orcid
        url: "#"
        title: Orcid
      - icon: ai ai-google-scholar
        url: "#"
        title: Google Scholar
      - icon: fab fa-researchgate
        url: "#"
        title: ResearchGate
  showInAccordion:
    - item: aboutme
      expand: true
    - item: experience
    #- item: education
    - item: publication
    #- item: project
    #- item: skill
    - item: hobby
  aboutme:
    title: 自己紹介
    icon: fas fa-user
    description: ミリアニ先行上映第2幕からの新人プロデューサーです。よろしくお願いします！
  experience:
    title: ミリシタ・ゲームID等
    icon: far fa-address-card
    list:
      - position: ID・名刺
        dates: 2023/9/20 - *なるみき 8RLKRF8Q*
        company: Company Name
        details: |1-
          - 同僚追加お気軽にどうぞ！
      - position: イベント実績(一部)
        details: |1-
          - 2023/10/18 - 10/25 · 解夏傀儡 [1771位]
  # education:
  #   title: Education
  #   icon: fas fa-graduation-cap
  #   list:
  #     - degree: Ph.D. in Subject
  #       college: University of State-City
  #       dates: 2013 - 2018
  #       thesis_title: "Effect of humans on other humans: a study of human behavior."
  #       thesis_url: "#"
  #     - degree: M.S. in Subject
  #       college: University of State-City
  #       dates: 2013 - 2018
  #       thesis_title: "Effect of humans on other humans: a study of human behavior."
  #       thesis_url: "#"
  #     - degree: B.S. in Subject
  #       college: University of State-City
  #       dates: 2004 - 2009
  publication:
    title: 参加したライブ・イベント
    icon: fas fa-book
    format:
      - date
      - title
      - Venue
      - at
    types:
      - ライブ
      - ライブ(2024年)
      - イベント
      - イベント(2024年)
      - Proceedings
    list:
      - title: >-
          THE IDOLM@STER 765 MILLIONSTARS HOTCHPOTCH FESTIV@L!! 2
        date: "2025/3/29・3/30"
        Venue: "さいたまスーパーアリーナ"
        url: "https://idolmaster-official.jp/live_event/hpf2/"
        at: 両日参加
        type: ライブ
      - title: >-
          THE IDOLM@STER MILLION LIVE! 10thLIVE TOUR Act-4 MILLION THE@TER!!!! 
        date: "2024/2/24・2/25"
        Venue: "Kアリーナ横浜"
        url: "https://idolmaster-official.jp/live_event/million10th/information/act4.php"
        type: ライブ(2024年)
        at: 両日参加
      - title: >-
          THE IDOLM@STER MILLION RADIO! SPECIAL PARTY 06
        date: "2025/6/15"
        Venue: "立川ステージガーデン"
        type: イベント
      - title: >-
          THE IDOLM@STER MILLION RADIO! SPECIAL PARTY 05
        date: "2024/5/12"
        Venue: "森のホール21(松戸市文化会館)大ホール"
        url: "#"
        type: イベント(2024年)
  # project:
  #   title: Projects
  #   icon: fas fa-project-diagram
  #   list:
  #     - title: Project 1
  #       url: "#"
  #       description: Description of the project
  #     - title: Project 2
  #       url: "#"
  #       description: Description of the project
  #     - title: Project 3
  #       url: "#"
  #       description: Description of the project
  #     - title: Project 4
  #       url: "#"
  #       description: Description of the project
  # skill:
  #   title: Skills
  #   panelId: skill-panel
  #   icon: fas fa-cogs
  #   list:
  #     - skill: "Skill 1, Skill 2"
  #       skillrating: 90
  #     - skill: Skill 3
  #       skillrating: 80
  #     - skill: Skill 4
  #       skillrating: 50
  hobby:
    title: その他趣味
    icon: fas fa-gamepad
    list:
      - hobby: 写真撮影()
      - hobby: 散歩
      - hobby: 読書
      - hobby: ポルノグラフィティ(LoveUp!会員 2024/9/7～)
